[package]
name = "smx-myinfo-cli"
version = "0.1.0"
authors = ["rumblefrog <contact@zhenyangli.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smxdasm = "0.1.0"
byteorder = "1.3.2"